spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blocklygames?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:

mybatis-plus:
  global-config:
    enable-sql-runner: true